apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: yemiwebby/aks-nodejs-argocd
  newTag: ce22bfc7583072f3fc6ad026457b0ae3d3df5f57
- name: argocd
  newName: azeezbabalola/argocd
  newTag: 0c237d3c37a003b75f3c070c1035a737d8a10a49
- name: my-node-app
  newName: azeezbabalola/my-node-app
  newTag: 426661a8d3ed762cbc807ec0bb6f9f1e23d9cf2f
